# Form implementation generated from reading ui file 'exitdialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_exit_dialog(object):
    def setupUi(self, exit_dialog):
        exit_dialog.setObjectName("exit_dialog")
        exit_dialog.resize(311, 154)
        exit_dialog.setStyleSheet("background-color: #fff")
        self.exit_btn = QtWidgets.QPushButton(parent=exit_dialog)
        self.exit_btn.setGeometry(QtCore.QRect(180, 110, 121, 31))
        self.exit_btn.setStyleSheet("background-color: #ff0000;\n"
"font-size: 14px;\n"
"")
        self.exit_btn.setObjectName("exit_btn")
        self.cansel_btn = QtWidgets.QPushButton(parent=exit_dialog)
        self.cansel_btn.setGeometry(QtCore.QRect(10, 110, 121, 31))
        self.cansel_btn.setStyleSheet("background: none;\n"
"border: none;\n"
"background-color: rgb(80, 80, 80)")
        self.cansel_btn.setObjectName("cansel_btn")
        self.label = QtWidgets.QLabel(parent=exit_dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 231, 31))
        self.label.setStyleSheet("font-size: 20px;\n"
"color: #000;\n"
"background:none;")
        self.label.setObjectName("label")

        self.retranslateUi(exit_dialog)
        QtCore.QMetaObject.connectSlotsByName(exit_dialog)

    def retranslateUi(self, exit_dialog):
        _translate = QtCore.QCoreApplication.translate
        exit_dialog.setWindowTitle(_translate("exit_dialog", "Dialog"))
        self.exit_btn.setText(_translate("exit_dialog", "Выйти"))
        self.cansel_btn.setText(_translate("exit_dialog", "Отмена"))
        self.label.setText(_translate("exit_dialog", "Вы точно хотите выйти?"))
